# This workflow will build a Python package and publish it to PyPI and Test PyPI when a new tag is pushed.

name: Publish to PyPI and Test PyPI

on:
  push:
    tags:
      - "v*"  # Trigger only if a tag starting with "v" is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Adjust as needed

    - name: Install dependencies
      run: |
        pip install build twine

    - name: Build the package
      run: python -m build

    - name: Determine Branch
      id: determine-branch
      run: echo "branch_name=$(echo ${GITHUB_REF} | sed 's|refs/heads/||; s|refs/tags/||')" >> $GITHUB_ENV

    - name: Publish to Test PyPI
      if: startsWith(github.ref, 'refs/tags/v') && github.ref_name == 'dev'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/v') && github.ref_name == 'main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
